In [2]:
from PIL import Image
import matplotlib.pyplot as plt
#%matplotlib inline
import numpy as np
import scipy
from scipy import ndimage
import matplotlib.pyplot as plt

In [14]:
im0 = Image.open("orig_0.jpg")
im1 = Image.open("orig_1.jpg")
im2 = Image.open("orig_2.jpg")
im3 = Image.open("orig_3.jpg")

In [15]:
im0.size

(816, 612)

In [16]:
id0 = np.array(im0.getdata())
id1 = np.array(im1.getdata())
id2 = np.array(im2.getdata())
id3 = np.array(im3.getdata())

id_comp = (id0+id1+id2+id3)/4

In [3]:
x = Image.open("test.jpg")
xd = np.array(x.getdata())

In [4]:
xd.shape

(48380, 3)

In [17]:
id_comp.size

1498176

In [18]:
id_comp

array([[38, 34, 24],
       [38, 33, 23],
       [40, 35, 24],
       ..., 
       [61, 54, 42],
       [60, 55, 42],
       [61, 55, 42]])

In [19]:
id_comp2 = np.reshape(id_comp, (612,816,3)).astype(np.uint8)

In [20]:
id_comp2.shape

(612, 816, 3)

In [21]:
im_comp = Image.fromarray(id_comp2, 'RGB')
im_comp.show()

In [22]:
im_comp.size

(816, 612)

### ColorMatrix for Saturation

In [23]:
orig_colorm = -0.2*np.array([[1,0,0], [0,1,0], [0,0,1]])
orig_colorm

array([[-0.2, -0. , -0. ],
       [-0. , -0.2, -0. ],
       [-0. , -0. , -0.2]])

In [24]:
lumR = 0.3086
lumG = 0.6094
lumB = 0.0820
s = 1.4 # saturation
c = 1.3 # contrast

In [25]:
satu = np.array([[(1-s)*lumR+s, (1-s)*lumR, (1-s)*lumR], [(1-s)*lumG, (1-s)*lumG+s, (1-s)*lumG], [(1-s)*lumB, (1-s)*lumB, (1-s)*lumB+s]])

In [26]:
cont = np.array([[c,0,0], [0,c,0], [0,0,c]])

In [27]:
new.shape

NameError: name 'new' is not defined

In [28]:
colorm = np.dot(np.dot(satu, cont), orig_colorm)
colorm 

array([[-0.3319056,  0.0320944,  0.0320944],
       [ 0.0633776, -0.3006224,  0.0633776],
       [ 0.008528 ,  0.008528 , -0.355472 ]])

In [29]:
new = np.dot(id_comp, colorm)
#new = np.dot(id_comp, orig_colorm)
new

array([[-10.2529024,  -8.7969024,  -5.1569024],
       [-10.324808 ,  -8.504808 ,  -4.864808 ],
       [-10.853336 ,  -9.033336 ,  -5.029336 ],
       ..., 
       [-16.4656752, -13.9176752,  -9.5496752],
       [-16.070392 , -14.250392 ,  -9.518392 ],
       [-16.4022976, -14.2182976,  -9.4862976]])

In [30]:
new2 = np.reshape(new, (612,816,3)).astype(np.uint8)

In [31]:
im_comp = Image.fromarray(new2, 'RGB')
im_comp.show()

In [251]:
sr = (1 - s) * lumR
sg = (1 - s) * lumG
sb = (1 - s) * lumB

In [252]:
im_y, im_x = Image.open("orig_0.jpg").size

In [259]:
mask = np.zeros(shape=(im_x*im_y, 3)).astype(np.float32)
for i in range(im_x*im_y):
    for j in range(3):
        if (j % 3 == 0):
            mask[i,j] = sr
        elif (j % 3 == 1):
            mask[i,j] = sg
        else:
            mask[i,j] = sb
print mask


[[-0.12344 -0.24376 -0.0328 ]
 [-0.12344 -0.24376 -0.0328 ]
 [-0.12344 -0.24376 -0.0328 ]
 ..., 
 [-0.12344 -0.24376 -0.0328 ]
 [-0.12344 -0.24376 -0.0328 ]
 [-0.12344 -0.24376 -0.0328 ]]


### Adding sharpening technique

In [7]:
#id3 = np.reshape(id_comp, (612,816,3)).astype(float)
blurred_f = ndimage.gaussian_filter(id_comp2, 3)
#blurred_f = ndimage.gaussian_filter(id3, 3)
filter_blurred_f = ndimage.gaussian_filter(blurred_f, 1)
alpha = 30
sharpened = blurred_f + alpha * (blurred_f - filter_blurred_f)

In [8]:
im_comp = Image.fromarray(sharpened, 'RGB')
im_comp.show()

#plt.figure(figsize=(12, 4))
#plt.imshow(sharpened, cmap=plt.cm.gray)
#plt.tight_layout()
#plt.show()

#### Using built-in function

In [20]:
import Image                 
import ImageFilter
x = im_comp.filter(ImageFilter.SHARPEN)    
#im_comp = Image.fromarray(x, 'RGB')
#im_comp.show()
#Image.filter(ImageFilter.EDGE_ENHANCE_MORE) 

plt.figure(figsize=(12, 4))
plt.imshow(x, cmap=plt.cm.gray)
plt.tight_layout()
plt.show()

# got similar resulting picture

/Users/xinyanhan/Documents/anaconda/lib/python2.7/site-packages/matplotlib/tight_layout.py:225: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")


In [24]:
im_comp.size

(816, 612)

In [116]:
import scipy
from scipy import ndimage
import matplotlib.pyplot as plt

f = scipy.misc.face(gray=True).astype(float)
blurred_f = ndimage.gaussian_filter(f, 3)

filter_blurred_f = ndimage.gaussian_filter(blurred_f, 1)

alpha = 30
sharpened = blurred_f + alpha * (blurred_f - filter_blurred_f)

plt.figure(figsize=(12, 4))

plt.subplot(131)
plt.imshow(f, cmap=plt.cm.gray)
plt.axis('off')
plt.subplot(132)
plt.imshow(blurred_f, cmap=plt.cm.gray)
plt.axis('off')
plt.subplot(133)
plt.imshow(sharpened, cmap=plt.cm.gray)
plt.axis('off')

plt.tight_layout()
plt.show()

In [32]:
 mask = [[0, -1, 0], [-1, 5, -1], [0, -1, 0]]

In [34]:
np.array(mask)

array([[ 0, -1,  0],
       [-1,  5, -1],
       [ 0, -1,  0]])

In [37]:
np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]]).astype(np.float32).shape

(3, 3)