### Masked image operations

A Numpy array mask is a boolean array that determines whether or not an operation is to be performed. If you have an image in a array, the mask allows you to work on only part of the image, ignoring the other part. This is useful for finding the mean of a selected region, or for computing a function that fits part of an image but ignores another part. 

In [60]:
from scipy import misc
import numpy as np

In [ ]:
''''
face = misc.face(gray=True)
face[0, 40]
127
# Slicing
face[10:13, 20:23]
array([[141, 153, 145],
       [133, 134, 125],
       [ 96,  92,  94]], dtype=uint8)
face[100:120] = 255
''''

In [45]:
face = misc.face(gray=True)

In [46]:
face

array([[114, 130, 145, ..., 119, 129, 137],
       [ 83, 104, 123, ..., 118, 134, 146],
       [ 68,  88, 109, ..., 119, 134, 145],
       ..., 
       [ 98, 103, 116, ..., 144, 143, 143],
       [ 94, 104, 120, ..., 143, 142, 142],
       [ 94, 106, 119, ..., 142, 141, 140]], dtype=uint8)

In [47]:
face.shape

(768, 1024)

In [48]:
face[0,40]

127

In [49]:
lx, ly = face.shape
lx

768

In [50]:
X, Y = np.ogrid[0:lx, 0:ly]

In [51]:
mask = (X - lx / 2) ** 2 + (Y - ly / 2) ** 2 > lx * ly / 4

In [52]:
mask.shape

(768, 1024)

In [53]:
mask

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ..., 
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]], dtype=bool)

In [54]:
face[mask] = 0

In [57]:
face[range(400), range(400)] = 255

In [59]:
import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4))
plt.imshow(face, cmap=plt.cm.gray)
plt.tight_layout()
plt.show()