In [14]:
from PIL import Image
import matplotlib.pyplot as plt
%matplotlib inline

In [20]:
im0 = Image.open("orig_0.jpg")
im1 = Image.open("orig_1.jpg")
im2 = Image.open("orig_2.jpg")
im3 = Image.open("orig_3.jpg")

In [24]:
im3.show()

In [25]:
plt.close()
plt.hist(im3.histogram())

(array([ 764.,    1.,    0.,    0.,    0.,    0.,    0.,    1.,    1.,    1.]),
 array([      0. ,   14487.5,   28975. ,   43462.5,   57950. ,   72437.5,
          86925. ,  101412.5,  115900. ,  130387.5,  144875. ]),
 <a list of 10 Patch objects>)

In [43]:
im0.getpixel((0,0))

(2, 2, 0)

In [40]:
len(im3.histogram())

768

In [41]:
?im3.histogram

In [44]:
im1.mode

'RGB'

In [50]:
im4 = Image.blend(im0,im3,alpha=0.5)

In [51]:
im4.show()

In [52]:
im0.show()

In [53]:
im3.show()

The blend function:

`out = image1 * (1.0 - alpha) + image2 * alpha`

In [54]:
im5 = Image.blend(im0,Image.blend(im1,Image.blend(im2, im3, 0.5),0.666667),0.75)

In [56]:
im5.show()

In [57]:
im0.show()

In [58]:
im3.show()

In [74]:
import numpy as np


In [89]:
id0 = np.array(im0.getdata())
id1 = np.array(im1.getdata())
id2 = np.array(im2.getdata())
id3 = np.array(im3.getdata())

id_comp = (id0+id1+id2+id3)/4

In [88]:
im0.size

(816, 612)

In [115]:
id_comp2 = np.reshape(id_comp, (612,816,3)).astype(np.uint8)

In [116]:
id_comp2.shape

(612, 816, 3)

In [117]:
id_comp2[1,2]

array([38, 33, 22], dtype=uint8)

In [118]:
im_comp = Image.fromarray(id_comp2, 'RGB')

In [119]:
im_comp.size

(816, 612)

In [120]:
im_comp.show()

In [78]:
im0.size

(816, 612)

In [79]:
816*612

499392

In [77]:
id0.shape

(499392, 3)

In [66]:
im0.point()

TypeError: point() takes at least 2 arguments (1 given)